In [7]:
import torch

# 创建一个目标张量
target = torch.zeros(3, 5)
print(f'target:\n{target}')

# 创建一个索引张量
index = torch.tensor([[0, 0, 0, 0, 0],
                      [0, 0, 0, 1, 2],
                      [0, 1, 1, 0, 1]])
print(f'index:\n{index}')

# 创建一个源张量
src = torch.tensor([[1, 2, 3, 4, 5],
                    [6, 7, 8, 9, 10],
                    [11, 12, 13, 14, 15]]).to(dtype=target.dtype)
print(f'src\n{src}')

# 沿着维度 1 进行散射操作
result = torch.scatter(target, 1, index, src)

print(f'result\n{result}')

target:
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
index:
tensor([[0, 1, 2, 0, 0],
        [2, 0, 0, 1, 2],
        [0, 1, 1, 0, 1]])
src
tensor([[ 1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10.],
        [11., 12., 13., 14., 15.]])
result
tensor([[ 5.,  2.,  3.,  0.,  0.],
        [ 8.,  9., 10.,  0.,  0.],
        [14., 15.,  0.,  0.,  0.]])


In [12]:
import torch

a = torch.arange(10)
print(a)

index = torch.randperm(5)[:3]
print(index)

a.scatter_(dim=0, index=index, value=0)
print(a)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([4, 2, 1])
tensor([0, 0, 0, 3, 0, 5, 6, 7, 8, 9])


In [2]:
import time

# # 获取当前时间
# current_time = time.localtime()

# 格式化时间为几点几分几秒
formatted_time = time.strftime("%H:%M:%S", time.localtime())

# 打印格式化后的时间
print(formatted_time)

12:36:27
